### ISSUE TITLE
English notebooks are filled with Chinese content... this needs to be translated properly

### ISSUE THREAD

**Issue by richlysakowski** [EgoAlpha/prompt-in-context-learning#2]
The content looks great, but as I went to use it, I found a lot of language problems (isn't that ironic for an LLM repo?).  

I cannot recommend this repository "as is" to my English-speaking colleagues and students because many parts of the "English" notebooks that are still in Chinese.  This does NOT appear to be intentional.

See for example:  https://github.com/EgoAlpha/prompt-in-context-learning/blob/main/langchain_guide/LangChainTutorial_en.ipynb

Yes, I know students could use LLMs to translate them, but the translations must be checked for accuracy with the intended meaning.  A Chinese LLM developer who knows English WELL needs to do that final proofreading.  

I appreciate your great efforts in putting this repository together, and sharing it with the English-speaking world.  These final translations will help make them accessible to many more people.  Thanks in advance for translating them. 

Thank you.  

Richard Lysakowki

**Comment by crescent73** [comment]
您好，我已收到您的来信!Hello, I've received your letter!

**Comment by cyfedu-dlut** [comment]
Thanks for the questions you pointed out, we will check off our repo in two days, and then, we will release the complete notebook in corresponding location of repo. Thanks again!

---- Replied Message ----
| From | Rich ***@***.***> |
| Date | 08/08/2023 12:40 |
| To | EgoAlpha/prompt-in-context-learning ***@***.***> |
| Cc | Subscribed ***@***.***> |
| Subject | [EgoAlpha/prompt-in-context-learning] English notebooks are filled with Chinese content... this needs to be translated properly (Issue #2) |

The content looks great, but as I went to use it, I found a lot of language problems (isn't that ironic for an LLM repo?).

I cannot recommend this repository "as is" to my English-speaking colleagues and students because many parts of the "English" notebooks that are still in Chinese. This does NOT appear to be intentional.

See for example: https://github.com/EgoAlpha/prompt-in-context-learning/blob/main/langchain_guide/LangChainTutorial_en.ipynb

Yes, I know students could use LLMs to translate them, but the translations must be checked for accuracy with the intended meaning. A Chinese LLM developer who knows English WELL needs to do that final proofreading.

I appreciate your great efforts in putting this repository together, and sharing it with the English-speaking world. These final translations will help make them accessible to many more people. Thanks in advance for translating them.

Thank you.

Richard Lysakowki

**Comment by EgoAlpha** [comment]
Thanks for your advice! We modified the contents that you mentioned above. Thanks again! Best wishes for you!
